import { z } from 'zod';
import { TimeframeThesis } from '../knowledge/hierarchical-types';
import { RelationalContext } from '../knowledge/relational-types';
import { ScenarioMemory } from '../knowledge/scenario-types';
import { TemporalState } from "../knowledge/temporal-types";
import { PMSO } from './pmso';

/**
 * The Hydration Context is the primary data structure for passing context down through the hierarchical analysis pipeline.
 * It allows higher-level orchestrators (like HTF) to provide a guiding thesis and context to lower-level orchestrators (like ITF and LTF).
 * This is the key to achieving a truly hierarchical and context-aware system.
 */
import { NewsEvent } from "../../core/news/news-types";
import { MarketDeliveryStateSchema } from "./canonical.js";


export const HydrationContextSchema = z.object({


  /** 
   * The thesis from the parent timeframe, which acts as the guiding context for the current timeframe's analysis. 
   * For example, the HTF orchestrator's output thesis becomes the `parent_thesis` for the ITF orchestrator.
   */
  parent_thesis: z.custom<TimeframeThesis>().optional(),

  /** 
   * A compressed summary of the most important facts and conclusions from the parent timeframe.
   * This is a more lightweight way to pass down context than the full `parent_thesis`.
   */
  minimal_context: z.any().optional(), // To be replaced with a specific schema in Phase 1

  /** The intermarket and macroeconomic context (e.g., DXY, SMT). */
  relational_context: z.custom<RelationalContext>().optional(),

  /** The set of plausible future scenarios generated by the ScenarioEngine. */
  scenario_context: z.custom<ScenarioMemory>().optional(),

  /** The most recent version of the Probabilistic Market State Object. */
  pmso_context: z.custom<PMSO>().optional(),

  inherited_temporal_state: z.custom<TemporalState>().nullable().optional(),

  // Preferred news hydration schema
  weekly_profile: z.any().optional(),
  daily_profile: z.any().optional(),
  raw_calendar_events: z.array(z.any()).optional(),

  // Legacy news layer kept temporarily for compatibility during migration
  news_events: z.custom<NewsEvent[]>().optional(),
  macro_events: z.array(z.any()).optional(),
  macro_profile: z.any().optional(),
  news_reasoning: z.array(z.any()).optional(),
  macro_narrative: z.any().optional(),
  event_windows: z.any().optional(),

  // Canonical Market Delivery State (additive-only; fields remain optional)
  market_delivery_state: MarketDeliveryStateSchema.optional(),
});


export type HydrationContext = z.infer<typeof HydrationContextSchema>;

