import { MarketScenario } from "../knowledge/scenario-types";

export type Confidence = number;

/**
 * A generic wrapper for any value in the system that is not a certainty.
 * It combines the value itself with a confidence score and metadata about how the value was derived.
 */
export type ProbabilisticValue<T> = {
  /** The actual value (e.g., "bullish", true, 101.5). */
  value: T;
  /** The confidence in the value, from 0.0 (no confidence) to 1.0 (full confidence). */
  confidence: Confidence;
  /** The component or agent that generated this value (e.g., "HTF-Orchestrator", "PMSOReconciler:Heuristic"). */
  source: string;
  /** A list of reasons or evidence that might contradict this value. */
  opposing_evidence: string[];
  /** A list of specific, observable market events (e.g., "Price breaks below 1.2500") that would invalidate this value. */
  invalidation_triggers: string[];
};

/**
 * Probabilistic Market State Object (PMSO)
 * This is the master data structure that represents the system's complete, reconciled understanding of the market at a given moment.
 * It is the final output of the reconciliation process and the primary input for the final decision-making LLM call.
 */
export interface PMSO {
  /** High-level context about the current market environment. */
  market_context: {
    /** The dominant directional bias derived from higher timeframes. */
    htf_bias: ProbabilisticValue<"bullish" | "bearish" | "neutral">;
    /** The current trading session (e.g., "NY_AM", "LONDON_CLOSE"). */
    current_session: ProbabilisticValue<string>;
    /** The state of liquidity (e.g., "internal_range", "external_range_liquidity_taken"). */
    liquidity_state: ProbabilisticValue<string>;
    /** The current market mode or profile (e.g., "consolidation", "expansion", "retracement"). */
    market_mode: ProbabilisticValue<string>;
  };
  /** Represents internal conflicts, disagreements, and alternative possibilities within the system's analysis. */
  tensions: {
    /** A numerical score (0-1) representing the degree of internal contradiction in the analysis. A high score indicates significant disagreement between agents or timeframes. */
    contradiction_score: number;
    /** A list of plausible alternative scenarios generated by the ScenarioEngine. These represent different paths the market could take. */
    alternative_scenarios: MarketScenario[];
  };
  /** Context derived from correlated assets and broader market factors. */
  intermarket: {
    /** Indicates if a Smart Money Technique (SMT) divergence has been detected between correlated assets. */
    smt_detected: ProbabilisticValue<boolean>;
    /** The directional pressure from macroeconomic factors (e.g., DXY, interest rates). */
    macro_pressure: ProbabilisticValue<"bullish" | "bearish" | "neutral">;
    macro_news_modifier?: {
      volatility_pressure?: number;
      uncertainty_pressure?: number;
      directional_alignment?: "ALIGNS" | "CONFLICTS" | "NEUTRAL";
      macro_context?: any;
      macro_ire?: any;
      event_windows?: any;
      execution_modifiers?: any;
      narrative_metadata?: any;
    };
  };
  /** The evolving state of market structures over time. */
  temporal_context?: {
    /** A list of all currently tracked market structures (e.g., FVGs, Order Blocks) and their status (active, tapped, invalidated). */
    active_structures: any[];
    /** A running narrative describing how the market state has evolved over the current session. */
    narrative: string;
  };
  /** Metadata about the PMSO itself. */
  metadata: {
    /** The ISO timestamp of when this PMSO was created. */
    last_updated: string;
    /** The unique identifier for the capture session this PMSO belongs to. */
    capture_id: string;
  };
}

/**
 * Represents a single, atomic piece of information extracted by an agent.
 * These are the raw building blocks that are later reconciled into the PMSO.
 */
export interface VisionFact {
  /** The type of concept or pattern identified (e.g., "FVG", "MarketStructureShift", "LiquiditySweep"). */
  type: string;
  /** The agent's confidence in this fact (0.0 to 1.0). */
  confidence: Confidence;
  /** A human-readable anchor describing the fact (e.g., "Bullish FVG at 1.2550", "MSS at 15:30 UTC"). */
  anchor: string;
  /** The timeframe on which this fact was observed (e.g., "M15", "H4", "DAILY"). */
  timeframe: string;
  /** The raw, unprocessed output from the agent that generated this fact, for debugging and traceability. */
  raw_output: any;
}
